### ISSUE TITLE
Very wrong PKGBUILD

### ISSUE THREAD

**Issue by bvaudour** [KaOS-Community-Packages/nss-mdns#1]
Never use the “sudo” command in a PKGBUILD. The repo will be removed in 2 days if not corrected.

Please, refer to the [KCP documentation](https://kaosx.us/docs/kcp/).

**Comment by panbroggi** [comment]
PKGBUILD has been corrected. Is this the correct way to set up the install?

**Comment by bvaudour** [comment]
Indeed. Closing the issue.
